name: update-docker-container

on:
  push:
    path:
      - Dockerfile
      - poetry.lock
      - pyproject.toml
    branches:
      - objetivo-5-test

jobs:
  update:  
    runs-on: ubuntu-latest
    steps: 
      - name: checkout
        uses: actions/checkout@v2

      - name: login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: arguellesm/faux

      - name: build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


